version: '3'
services:
  angular-frontend:
    image: alarassaa/repo2:tpachattag-angular-${BUILD_NUMBER}
    ports:
      - "4200:80"     # Expose port 4200 to access Angular app
    restart: always   # Restart the container automatically if it crashes or stops

  spring-backend:
    image: alarassaa/repo1:tpachattag # Ensure this Docker image exists with the correct tag on Docker Hub
    ports:
      - "8089:8089"   # Expose port 8089 for Spring Boot API
    restart: always   # Optional: Allow automatic restart of the Spring Boot container if it crashes
