version: '3'
services:
  angular-frontend:
    image: alarassaa/repo2:tpachattag-angular-${BUILD_NUMBER}
    ports:
      - "4200:80"     # Expose port 4200 to access Angular app
    restart: always   # Restart the container automatically if it stops

  spring-backend:
    image: alarassaa/repo1:tpachat # Assuming your Spring app has been dockerized in another repo
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achat_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    depends_on:       # Ensure Spring Boot starts first
      - angular-frontend
    restart: always
